"""
sequence_viewer.py
------------------
Sequence-Viewer integration layer for StructureBot.

Two capabilities:

PART A — bidirectional click highlighting.
  Native in ChimeraX once a chain's sequence is shown + associated in the
  Sequence Viewer (selecting in 3D highlights the column; dragging on the
  sequence selects in 3D).  `ensure_sequence_viewer_commands()` returns the
  ChimeraX commands to open + associate the viewer for a model's chains, so any
  view (not just the MPNN alignment flow) can enable it.

PART B — SCF coloring mirror.
  Mirror a per-residue structural colouring onto the sequence as coloured
  regions.  ChimeraX 1.11.1 does NOT load a Sequence-Coloring-Format (`.scf`)
  file via the REST `open` command ("Unrecognized file suffix '.scf'"), so we
  write the `.scf` (the portable data file) AND a tiny `runscript` `.py` that
  reads it and drives the Sequence Viewer's Python region API
  (`SequenceViewer.new_region(name=, blocks=[(seq0, seqN, col0, col1)],
  fill=(r,g,b))`).  The REST command is `runscript "<py>"`.

SCF line format (one per coloured position)::

    <alignment_pos_0based>\t<seq_index>\t<R>\t<G>\t<B>\t// <region_name>

  seq_index 0 = all sequences; RGB are 0-255.  Alignment positions are 0-based;
  PDB residue numbers are converted via the canonical
  `proteinmpnn_bridge.chain_resnum_to_seqpos` (1-based chain order) minus 1, so
  chains that don't start at residue 1 (or have gaps) map correctly.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

RGB = Tuple[int, int, int]


def _clamp8(v) -> int:
    """Clamp a value to a 0-255 integer channel."""
    try:
        iv = int(round(float(v)))
    except (TypeError, ValueError):
        iv = 0
    return max(0, min(255, iv))


# ── PART B: SCF coloring ────────────────────────────────────────────────────────

def build_scf_file(
    residue_colors:  Dict[int, RGB],
    ordered_resnums: Sequence[int],
    out_path:        Path,
    seq_index:       int = 0,
    region_name:     str = "region",
) -> str:
    """
    Write a Sequence-Coloring-Format (.scf) file and return its POSIX path.

    Parameters
    ----------
    residue_colors  : {pdb_residue_number: (r, g, b)} — the SAME per-residue RGB
                      a bridge uses for structure colouring.  RGB are clamped to
                      0-255.
    ordered_resnums : the chain's residue numbers in sequence order (handles a
                      non-1 start and numbering gaps).  Used to convert each
                      residue number to its 0-based alignment position.
    out_path        : where to write the .scf (parents created).
    seq_index       : SCF sequence index (0 = colour all sequences/rows).
    region_name     : comment label written after `//` on every line.

    Residue numbers absent from *ordered_resnums* are skipped (can't be placed
    on the alignment).
    """
    from proteinmpnn_bridge import chain_resnum_to_seqpos
    pos1 = chain_resnum_to_seqpos(ordered_resnums)   # resnum -> 1-based position

    lines: List[str] = []
    for resnum in sorted(residue_colors):
        if resnum not in pos1:
            continue
        pos0 = pos1[resnum] - 1                       # SCF is 0-based
        r, g, b = (_clamp8(c) for c in residue_colors[resnum])
        lines.append(f"{pos0}\t{int(seq_index)}\t{r}\t{g}\t{b}\t// {region_name}")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(("\n".join(lines) + "\n") if lines else "", encoding="utf-8")
    return out_path.as_posix()


# Loader template: reads an .scf and applies it as Sequence-Viewer regions.
# `session` is injected as a global when ChimeraX runs the script via `runscript`.
_SCF_APPLY_TEMPLATE = '''\
# AUTO-GENERATED by StructureBot sequence_viewer.build_scf_runscript — do not edit.
# Loads a .scf coloring into the open ChimeraX Sequence Viewer via new_region,
# because `open *.scf` is unsupported over REST in ChimeraX 1.11.1.
_SCF_PATH = r"__SCF_PATH__"
_NAME_PREFIX = "__NAME_PREFIX__"


def _apply(session):
    sv = None
    for t in session.tools.list():
        if type(t).__name__ == "SequenceViewer":
            sv = t
            break
    if sv is None:
        return
    seqs = list(sv.alignment.seqs)
    if not seqs:
        return

    # Best-effort: clear any prior regions we created (idempotent re-runs).
    try:
        rm = getattr(sv, "region_manager", None)
        regs = list(getattr(rm, "regions", []) or [])
        for r in regs:
            if getattr(r, "name", None) and str(r.name).startswith(_NAME_PREFIX):
                try:
                    rm.delete_region(r)
                except Exception:
                    try:
                        r.set_shown(False)
                    except Exception:
                        pass
    except Exception:
        pass

    groups = {}   # (r,g,b,name) -> [(seq0, seqN, col, col), ...]
    try:
        with open(_SCF_PATH) as fh:
            scf_lines = fh.readlines()
    except Exception:
        return
    for line in scf_lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name = "region"
        if "//" in line:
            body, _, comment = line.partition("//")
            name = comment.strip() or "region"
        else:
            body = line
        parts = body.split()
        if len(parts) < 5:
            continue
        try:
            pos = int(parts[0]); si = int(parts[1])
            rr = int(parts[2]); gg = int(parts[3]); bb = int(parts[4])
        except ValueError:
            continue
        if si == 0:
            s0, s1 = seqs[0], seqs[-1]
        elif 1 <= si <= len(seqs):
            s0 = s1 = seqs[si - 1]
        else:
            continue
        groups.setdefault((rr, gg, bb, name), []).append((s0, s1, pos, pos))

    for (rr, gg, bb, name), blocks in groups.items():
        try:
            sv.new_region(name=_NAME_PREFIX + name, blocks=blocks, fill=(rr, gg, bb))
        except Exception:
            pass


_apply(session)
'''


def build_scf_runscript(
    scf_posix:   str,
    out_py_path: Path,
    name_prefix: str = "StructureBot:",
) -> str:
    """
    Write a `runscript` loader for *scf_posix* and return the REST command
    `runscript "<py>"` that applies it to the open Sequence Viewer.

    `open *.scf` is unsupported over REST in ChimeraX 1.11.1, so this loader
    drives the Sequence Viewer's `new_region` Python API instead.  Regions are
    named ``<name_prefix><region>`` so re-runs can clear the previous set.
    """
    script = (_SCF_APPLY_TEMPLATE
              .replace("__SCF_PATH__", scf_posix)
              .replace("__NAME_PREFIX__", name_prefix))
    out_py_path = Path(out_py_path)
    out_py_path.parent.mkdir(parents=True, exist_ok=True)
    out_py_path.write_text(script, encoding="utf-8")
    return f'runscript "{out_py_path.as_posix()}"'


# ── PART A: viewer setup + mouse mode ───────────────────────────────────────────

def ensure_sequence_viewer_commands(
    model_id: str,
    chains:   Optional[Sequence[str]] = None,
) -> List[str]:
    """
    ChimeraX commands that open + associate the Sequence Viewer for a model's
    chain(s).  `sequence chain #<model>/<chain>` shows the chain's own sequence,
    which ChimeraX auto-associates with the structure — enabling bidirectional
    click highlighting (3D selection ↔ sequence column).

    With *chains* = None, shows the whole model's sequences.
    """
    if not chains:
        return [f"sequence chain #{model_id}"]
    cmds: List[str] = []
    for ch in chains:
        spec = f"#{model_id}/{ch}" if ch else f"#{model_id}"
        cmds.append(f"sequence chain {spec}")
    return cmds


def left_click_select_command(enable: bool) -> str:
    """
    Toggle PyMOL-style plain left-click selection.

    enable=True  → `mousemode left select` (left-click selects; trades away the
                   default left-drag rotate).
    enable=False → `mousemode left rotate` (restore the default).
    """
    return "mousemode left select" if enable else "mousemode left rotate"
