"""
sequence_viewer.py
------------------
Sequence-Viewer integration layer for StructureBot.

Two capabilities:

PART A — bidirectional click highlighting.
  Native in ChimeraX once a chain's sequence is shown + associated in the
  Sequence Viewer (selecting in 3D highlights the column; dragging on the
  sequence selects in 3D).  `ensure_sequence_viewer_commands()` returns the
  ChimeraX commands to open + associate the viewer for a model's chains, so any
  view (not just the MPNN alignment flow) can enable it.

PART B — SCF coloring mirror.
  Mirror a per-residue structural colouring onto the sequence as coloured
  regions.  ChimeraX 1.11.1 does NOT load a Sequence-Coloring-Format (`.scf`)
  file via the REST `open` command ("Unrecognized file suffix '.scf'"), so we
  write the `.scf` (the portable data file) AND a tiny `runscript` `.py` that
  reads it and drives the Sequence Viewer's Python region API
  (`SequenceViewer.new_region(name=, blocks=[(seq0, seqN, col0, col1)],
  fill=(r,g,b))`).  The REST command is `runscript "<py>"`.

SCF line format (one per coloured position)::

    <alignment_pos_0based>\t<seq_index>\t<R>\t<G>\t<B>\t// <region_name>

  seq_index 0 = all sequences; RGB are 0-255.  Alignment positions are 0-based;
  PDB residue numbers are converted via the canonical
  `proteinmpnn_bridge.chain_resnum_to_seqpos` (1-based chain order) minus 1, so
  chains that don't start at residue 1 (or have gaps) map correctly.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

RGB = Tuple[int, int, int]


def _clamp8(v) -> int:
    """Clamp a value to a 0-255 integer channel."""
    try:
        iv = int(round(float(v)))
    except (TypeError, ValueError):
        iv = 0
    return max(0, min(255, iv))


# ── PART B: SCF coloring ────────────────────────────────────────────────────────

def build_scf_file(
    residue_colors:  Dict[int, RGB],
    ordered_resnums: Sequence[int],
    out_path:        Path,
    seq_index:       int = 0,
    region_name:     str = "region",
) -> str:
    """
    Write a Sequence-Coloring-Format (.scf) file and return its POSIX path.

    Parameters
    ----------
    residue_colors  : {pdb_residue_number: (r, g, b)} — the SAME per-residue RGB
                      a bridge uses for structure colouring.  RGB are clamped to
                      0-255.
    ordered_resnums : the chain's residue numbers in sequence order (handles a
                      non-1 start and numbering gaps).  Used to convert each
                      residue number to its 0-based alignment position.
    out_path        : where to write the .scf (parents created).
    seq_index       : SCF sequence index (0 = colour all sequences/rows).
    region_name     : comment label written after `//` on every line.

    Residue numbers absent from *ordered_resnums* are skipped (can't be placed
    on the alignment).
    """
    from proteinmpnn_bridge import chain_resnum_to_seqpos
    pos1 = chain_resnum_to_seqpos(ordered_resnums)   # resnum -> 1-based position

    lines: List[str] = []
    for resnum in sorted(residue_colors):
        if resnum not in pos1:
            continue
        pos0 = pos1[resnum] - 1                       # SCF is 0-based
        r, g, b = (_clamp8(c) for c in residue_colors[resnum])
        lines.append(f"{pos0}\t{int(seq_index)}\t{r}\t{g}\t{b}\t// {region_name}")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(("\n".join(lines) + "\n") if lines else "", encoding="utf-8")
    return out_path.as_posix()


# Loader template: reads an .scf and applies it as Sequence-Viewer regions.
# `session` is injected as a global when ChimeraX runs the script via `runscript`.
_SCF_APPLY_TEMPLATE = '''\
# AUTO-GENERATED by StructureBot sequence_viewer.build_scf_runscript — do not edit.
# Loads a .scf coloring into the open ChimeraX Sequence Viewer via new_region,
# because `open *.scf` is unsupported over REST in ChimeraX 1.11.1.
_SCF_PATH = r"__SCF_PATH__"
_NAME_PREFIX = "__NAME_PREFIX__"


def _apply(session):
    sv = None
    for t in session.tools.list():
        if type(t).__name__ == "SequenceViewer":
            sv = t
            break
    if sv is None:
        return
    seqs = list(sv.alignment.seqs)
    if not seqs:
        return

    # Best-effort: clear any prior regions we created (idempotent re-runs).
    try:
        rm = getattr(sv, "region_manager", None)
        regs = list(getattr(rm, "regions", []) or [])
        for r in regs:
            if getattr(r, "name", None) and str(r.name).startswith(_NAME_PREFIX):
                try:
                    rm.delete_region(r)
                except Exception:
                    try:
                        r.set_shown(False)
                    except Exception:
                        pass
    except Exception:
        pass

    groups = {}   # (r,g,b,name) -> [(seq0, seqN, col, col), ...]
    try:
        with open(_SCF_PATH) as fh:
            scf_lines = fh.readlines()
    except Exception:
        return
    for line in scf_lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name = "region"
        if "//" in line:
            body, _, comment = line.partition("//")
            name = comment.strip() or "region"
        else:
            body = line
        parts = body.split()
        if len(parts) < 5:
            continue
        try:
            pos = int(parts[0]); si = int(parts[1])
            rr = int(parts[2]); gg = int(parts[3]); bb = int(parts[4])
        except ValueError:
            continue
        if si == 0:
            s0, s1 = seqs[0], seqs[-1]
        elif 1 <= si <= len(seqs):
            s0 = s1 = seqs[si - 1]
        else:
            continue
        groups.setdefault((rr, gg, bb, name), []).append((s0, s1, pos, pos))

    for (rr, gg, bb, name), blocks in groups.items():
        try:
            sv.new_region(name=_NAME_PREFIX + name, blocks=blocks, fill=(rr, gg, bb))
        except Exception:
            pass


_apply(session)
'''


def build_scf_runscript(
    scf_posix:   str,
    out_py_path: Path,
    name_prefix: str = "StructureBot:",
) -> str:
    """
    Write a `runscript` loader for *scf_posix* and return the REST command
    `runscript "<py>"` that applies it to the open Sequence Viewer.

    `open *.scf` is unsupported over REST in ChimeraX 1.11.1, so this loader
    drives the Sequence Viewer's `new_region` Python API instead.  Regions are
    named ``<name_prefix><region>`` so re-runs can clear the previous set.
    """
    script = (_SCF_APPLY_TEMPLATE
              .replace("__SCF_PATH__", scf_posix)
              .replace("__NAME_PREFIX__", name_prefix))
    out_py_path = Path(out_py_path)
    out_py_path.parent.mkdir(parents=True, exist_ok=True)
    out_py_path.write_text(script, encoding="utf-8")
    return f'runscript "{out_py_path.as_posix()}"'


# ── PART A: viewer setup + mouse mode ───────────────────────────────────────────

def ensure_sequence_viewer_commands(
    model_id: str,
    chains:   Optional[Sequence[str]] = None,
) -> List[str]:
    """
    ChimeraX commands that open + associate the Sequence Viewer for a model's
    chain(s).  `sequence chain #<model>/<chain>` shows the chain's own sequence,
    which ChimeraX auto-associates with the structure — enabling bidirectional
    click highlighting (3D selection ↔ sequence column).

    With *chains* = None, shows the whole model's sequences.
    """
    if not chains:
        return [f"sequence chain #{model_id}"]
    cmds: List[str] = []
    for ch in chains:
        spec = f"#{model_id}/{ch}" if ch else f"#{model_id}"
        cmds.append(f"sequence chain {spec}")
    return cmds


# Reusable runscript that docks EVERY open Sequence Viewer along the BOTTOM edge,
# stacked vertically (so each chain's sequence is visible at once and selectable
# independently). ChimeraX docks the viewer at the top by default and has no REST
# command to set a tool's dock area, so this drives the Qt QDockWidget directly
# (`main_window.addDockWidget` + `splitDockWidget`) — verified on ChimeraX 1.11.1.
# Best-effort: any failure is swallowed so an open is never disrupted.
_DOCK_BOTTOM_TEMPLATE = '''\
# AUTO-GENERATED by StructureBot sequence_viewer.dock_sequences_bottom_command — do not edit.
# Re-docks the open Sequence Viewer(s) to the bottom edge, stacked vertically.
def _dock(session):
    try:
        from Qt.QtCore import Qt
    except Exception:
        return
    mw = getattr(getattr(session, "ui", None), "main_window", None)
    if mw is None:
        return
    svs = []
    for t in session.tools.list():
        if type(t).__name__ != "SequenceViewer":
            continue
        tw = getattr(t, "tool_window", None)
        dw = getattr(tw, "_dock_widget", None) if tw is not None else None
        if dw is None:
            continue
        key = ""
        try:
            key = str(getattr(t.alignment, "ident", "") or "")
        except Exception:
            pass
        svs.append((key or str(getattr(t, "display_name", "")), dw))
    # stable order: chain A above chain B above chain C ...
    svs.sort(key=lambda x: x[0])
    prev = None
    for _key, dw in svs:
        try:
            dw.setFloating(False)
            mw.addDockWidget(Qt.BottomDockWidgetArea, dw)
            if prev is not None:
                mw.splitDockWidget(prev, dw, Qt.Vertical)
            dw.show()
            prev = dw
        except Exception:
            continue


_dock(session)
'''


def dock_sequences_bottom_command(out_py_path: Optional[Path] = None) -> str:
    """
    Write the dock-at-bottom-stacked loader and return the REST command
    ``runscript "<py>"`` that re-docks every open Sequence Viewer along the bottom
    edge, stacked vertically.

    ChimeraX docks the Sequence Viewer at the top by default and exposes no REST
    command to move it, so the loader drives the Qt dock widget directly (verified
    on 1.11.1).  Idempotent — safe to run after every open.
    """
    if out_py_path is None:
        import config
        out_py_path = Path(config.SEQVIEW_CACHE_DIR) / "dock_sequences_bottom.py"
    out_py_path = Path(out_py_path)
    out_py_path.parent.mkdir(parents=True, exist_ok=True)
    out_py_path.write_text(_DOCK_BOTTOM_TEMPLATE, encoding="utf-8")
    return f'runscript "{out_py_path.as_posix()}"'


# ── PART C: residue-number ruler (custom fixed header) ──────────────────────────
# ChimeraX 1.11.1's native Sequence-Viewer numbering is POSITION-based
# (`seq_canvas._compute_numbering` = `numbering_start + count`, a linear offset that
# reads 1..N regardless of the chain's real residue numbers and can't honor gaps —
# probed live: 1IL8 chain A starts at resnum 2 but `numbering_start` is 1). So we
# add a CUSTOM fixed header whose contents spell out the ACTUAL PDB residue numbers
# every N residues, placed via the canonical `chain_resnum_to_seqpos` map (the same
# resnum↔1-based-position map the MPNN/SCF flow uses → the ruler is consistent with
# the MPNN alignment numbering). The header is added per chain over REST via a
# runscript (the same channel as the SCF region loader), because there is no
# `sequence`/REST command to set a numbering ruler.

def build_numbering_header_content(
    ordered_resnums: Sequence[int], interval: int = 10,
) -> str:
    """
    Build the per-column RULER string for a chain's Sequence Viewer: one character
    per residue column, spaces except where a residue number is printed every
    *interval* residues (and at the last residue).

    The labels are the ACTUAL PDB residue numbers — `ordered_resnums` is the chain's
    residue numbers in SEQUENCE order (handles a non-1 start and numbering gaps), and
    each label is placed at its column via `chain_resnum_to_seqpos` (so it matches the
    MPNN alignment numbering). A non-1-start chain (e.g. starts at 2) therefore reads
    2,12,22… NOT 1,11,21. Each number's UNITS digit sits at its residue column (the
    digits extend leftward, FASTA-ruler style; clamped at the left edge).
    """
    from proteinmpnn_bridge import chain_resnum_to_seqpos
    n = len(ordered_resnums)
    if n == 0 or interval < 1:
        return " " * n
    pos1 = chain_resnum_to_seqpos(ordered_resnums)      # resnum -> 1-based position
    chars = [" "] * n
    label_idxs = list(range(0, n, interval))
    last = n - 1
    if last not in label_idxs:                          # label the last residue too,
        prev = label_idxs[-1]                            # unless it would crowd/merge
        if last - prev > len(str(int(ordered_resnums[last]))):  # into the previous label
            label_idxs.append(last)
    for idx in label_idxs:
        resnum = int(ordered_resnums[idx])
        col = pos1[resnum] - 1                           # 0-based column (== idx here)
        s = str(resnum)
        start = max(0, col - (len(s) - 1))               # units digit at the column
        for i, ch in enumerate(s):
            c = start + i
            if 0 <= c < n:
                chars[c] = ch
    return "".join(chars)


# Loader template: adds the ruler as a fixed header to the per-chain viewer whose
# alignment identifier is "<model>/<chain>". Best-effort throughout (a numbering
# failure must never disrupt an open). Idempotent — destroys a prior ruler header
# of the same name first, and pads/truncates the content to the viewer's own length
# (the viewer's SEQRES sequence can differ from the resolved residue count).
_NUMBERING_TEMPLATE = '''\
# AUTO-GENERATED by StructureBot sequence_viewer.numbering_header_command — do not edit.
# Adds a residue-number ruler (custom fixed header) to one per-chain Sequence Viewer.
_IDENT = "__IDENT__"
_NAME = "__NAME__"
_CONTENT = __CONTENT_REPR__


def _add(session):
    sv = None
    for t in session.tools.list():
        if type(t).__name__ != "SequenceViewer":
            continue
        try:
            if str(getattr(t.alignment, "ident", "")) == _IDENT:
                sv = t
                break
        except Exception:
            pass
    if sv is None:
        return
    al = sv.alignment
    seqs = list(getattr(al, "seqs", []) or [])
    if not seqs:
        return
    try:
        length = len(seqs[0].ungapped())
    except Exception:
        length = len(_CONTENT)
    content = _CONTENT
    if len(content) < length:
        content = content + " " * (length - len(content))
    elif len(content) > length:
        content = content[:length]
    # idempotent: drop a prior ruler of the same name before re-adding
    for h in list(getattr(al, "headers", []) or []):
        try:
            if getattr(h, "name", None) == _NAME:
                h.destroy()
        except Exception:
            pass
    try:
        al.add_fixed_header(_NAME, content, shown=True)
    except Exception:
        pass


_add(session)
'''

_NUMBERING_HEADER_NAME = "Numbering"


def numbering_header_command(
    model_id: str,
    chain: str,
    ordered_resnums: Sequence[int],
    interval: int = 10,
    out_py_path: Optional[Path] = None,
) -> str:
    """
    Write the ruler loader for one chain and return the REST command
    ``runscript "<py>"`` that adds it to that chain's Sequence Viewer. Returns ``""``
    when there is nothing to label (no resnums), so the caller emits no command.
    """
    content = build_numbering_header_content(ordered_resnums, interval)
    if not content.strip():
        return ""
    script = (_NUMBERING_TEMPLATE
              .replace("__IDENT__", f"{model_id}/{chain}")
              .replace("__NAME__", _NUMBERING_HEADER_NAME)
              .replace("__CONTENT_REPR__", repr(content)))
    if out_py_path is None:
        import config
        out_py_path = Path(config.SEQVIEW_CACHE_DIR) / f"numbering_{model_id}_{chain}.py"
    out_py_path = Path(out_py_path)
    out_py_path.parent.mkdir(parents=True, exist_ok=True)
    out_py_path.write_text(script, encoding="utf-8")
    return f'runscript "{out_py_path.as_posix()}"'


def left_click_select_command(enable: bool) -> str:
    """
    Toggle PyMOL-style plain left-click selection.

    enable=True  → `mousemode left select` (left-click selects; trades away the
                   default left-drag rotate).
    enable=False → `mousemode left rotate` (restore the default).
    """
    return "mousemode left select" if enable else "mousemode left rotate"


# ── PART D: consolidated sequence-viewer grouping ───────────────────────────────
# For structures with many chains (e.g. hemoglobin α2β2), opening one per-chain
# viewer per chain letterboxes the 3D view. Consolidation groups chains with
# IDENTICAL sequences (same AA string AND same residue numbering) into ONE alignment
# window, with one row per open structure. Chain addressability is unaffected:
# `#N/A` targeting works regardless of what viewers are open.
#
# Probe-verified on ChimeraX 1.11.1 (2026-06-06):
#   • session.alignments.new_alignment([chain_A, chain_B], identify_as="ident")
#     auto-associates ALL chains with matching sequences across ALL open models →
#     selecting a row selects every copy in 3D (the native auto-association).
#   • add_fixed_header(name, content) works on multi-row alignments when
#     len(content) == alignment length (same requirement as single-row case).
#   • new_alignment auto-destroys any existing alignment with the same ident.
#   • sequence chain #N/A (disentangle) destroys any N/A alignment then creates
#     a standalone per-chain viewer — the existing mechanism, unchanged.
#   • select #1/A is unaffected by what viewers are open (display ≠ addressing).

# Ruler algorithm is the SAME as build_numbering_header_content; the runscript
# replicates it so it runs inside ChimeraX (where chain objects are accessible)
# without a separate REST round-trip per chain.
_CONSOLIDATE_TEMPLATE = '''\
# AUTO-GENERATED by StructureBot sequence_viewer.consolidated_viewers_command — do not edit.
# Groups all open multi-chain structures into one Sequence Viewer per unique
# sequence group. DISPLAY ONLY — `#N/<chain>` targeting is unaffected.
import hashlib as _hashlib

_THRESHOLD = __THRESHOLD__
_CAP       = __CAP__
_INTERVAL  = __INTERVAL__
_NUMBERING = __NUMBERING__


def _reconsolidate(session):
    try:
        # ── collect chains from models in consolidation range ────────────────
        # Only structures with THRESHOLD < n_chains <= CAP are consolidated;
        # smaller structures use per-chain viewers, larger use the whole-model viewer.
        by_group = {}       # key -> {mid_str: {"rep": chain, "label": str, "cids": [str]}}
        rns_for_group = {}  # key -> resnums_tuple

        for m in session.models:
            if not hasattr(m, "chains"):
                continue
            protein_chains = [c for c in m.chains if len(c.characters) > 0]
            n = len(protein_chains)
            if n <= _THRESHOLD or n > _CAP:
                continue
            model_label = (getattr(m, "name", None) or str(m.id[0])).upper()
            mid_str = ".".join(str(x) for x in m.id)
            for c in protein_chains:
                seq = c.characters
                try:
                    rns = tuple(sorted(r.number for r in c.existing_residues))
                except Exception:
                    rns = tuple(range(1, len(seq) + 1))
                seq_hash = _hashlib.md5(seq.encode()).hexdigest()[:12]
                key = (seq_hash, rns)
                if key not in by_group:
                    by_group[key] = {}
                    rns_for_group[key] = rns
                if mid_str not in by_group[key]:
                    by_group[key][mid_str] = {
                        "rep": c, "label": model_label, "cids": []
                    }
                by_group[key][mid_str]["cids"].append(c.chain_id)

        if not by_group:
            return

        # ── create / replace one alignment per group ─────────────────────────
        for key, models_dict in by_group.items():
            seq_hash, rns = key
            group_ident = "grp_" + seq_hash

            # Sort representatives by model id for stable row ordering
            reps_info = []
            for mid_str in sorted(models_dict.keys()):
                e = models_dict[mid_str]
                chain_ids = sorted(set(e["cids"]))
                reps_info.append((e["rep"], e["label"], chain_ids))

            reps = [ri[0] for ri in reps_info]
            # new_alignment auto-destroys any prior alignment with same ident
            al = session.alignments.new_alignment(reps, identify_as=group_ident)

            # Label each row "MODEL:A,C" so the user knows which chains it covers
            try:
                seqs = list(al.seqs)
                for i, (_rep, label, chain_ids) in enumerate(reps_info):
                    if i < len(seqs):
                        try:
                            seqs[i].name = label + ":" + ",".join(chain_ids)
                        except Exception:
                            pass
            except Exception:
                pass

            # ── residue-number ruler (same algorithm as build_numbering_header_content)
            if _NUMBERING and rns:
                try:
                    n = len(rns)
                    pos1 = {rn: i + 1 for i, rn in enumerate(rns)}
                    chars = [" "] * n
                    label_idxs = list(range(0, n, _INTERVAL))
                    last_i = n - 1
                    if last_i not in label_idxs:
                        prev = label_idxs[-1] if label_idxs else 0
                        if last_i - prev > len(str(rns[-1])):
                            label_idxs.append(last_i)
                    for ri in label_idxs:
                        rn = rns[ri]
                        col = pos1[rn] - 1
                        s = str(rn)
                        start = max(0, col - (len(s) - 1))
                        for ci, ch in enumerate(s):
                            c = start + ci
                            if 0 <= c < n:
                                chars[c] = ch
                    ruler = "".join(chars)
                    seqs = list(al.seqs)
                    if seqs:
                        length = len(seqs[0].ungapped())
                        ruler = (ruler + " " * length)[:length]
                    # Clear any prior Numbering header before re-adding
                    for h in list(getattr(al, "headers", []) or []):
                        if getattr(h, "name", "") == "Numbering":
                            try:
                                h.destroy()
                            except Exception:
                                pass
                    al.add_fixed_header("Numbering", ruler, shown=True)
                except Exception:
                    pass
    except Exception:
        pass


_reconsolidate(session)
'''


def consolidated_viewers_command(
    threshold: int = 3,
    cap: int = 8,
    interval: int = 10,
    numbering: bool = True,
    out_py_path: Optional[Path] = None,
) -> str:
    """
    Write the consolidated-viewer runscript and return the REST command
    ``runscript "<py>"`` that re-groups all open multi-chain structures into one
    Sequence Viewer per unique sequence group.

    Structures with ``threshold < n_chains <= cap`` are consolidated; those outside
    that range use per-chain or whole-model viewers managed by the bridge.  Idempotent
    — safe to call again after a sequence edit (dynamic regroup) or a new model open.

    Probe-verified on ChimeraX 1.11.1: ``new_alignment`` auto-associates all chains
    with matching sequences across all open models; ``add_fixed_header`` works on
    multi-row alignments when content length == alignment length.
    """
    script = (_CONSOLIDATE_TEMPLATE
              .replace("__THRESHOLD__", str(int(threshold)))
              .replace("__CAP__",       str(int(cap)))
              .replace("__INTERVAL__",  str(int(interval)))
              .replace("__NUMBERING__", "True" if numbering else "False"))
    if out_py_path is None:
        import config
        out_py_path = Path(config.SEQVIEW_CACHE_DIR) / "consolidate_viewers.py"
    out_py_path = Path(out_py_path)
    out_py_path.parent.mkdir(parents=True, exist_ok=True)
    out_py_path.write_text(script, encoding="utf-8")
    return f'runscript "{out_py_path.as_posix()}"'


def disentangle_chain_command(model_id: str, chain: str) -> str:
    """
    ChimeraX command to open a STANDALONE per-chain sequence viewer for one chain,
    breaking it out of any consolidated group alignment for inspection or editing.

    This is the existing ``sequence chain #N/A`` mechanism: ChimeraX auto-destroys
    any pre-existing alignment with ident ``N/A`` and creates a fresh per-chain
    viewer with the chain's own ruler. The group alignment is left intact (the chain
    still appears there for overview); the standalone viewer provides the per-residue
    focus needed for editing.

    Chain addressability (``#N/A`` targeting) is unaffected by either viewer.
    """
    return f"sequence chain #{model_id}/{chain}"


def resolve_group_edit_target(
    group_chains: List[str],
    requested_chain: Optional[str],
) -> Tuple[Optional[List[str]], Optional[str]]:
    """
    For an edit targeting a consolidated (grouped) row, determine the concrete
    target chain(s).

    Returns ``(chains, disambiguation_msg)``:

    * ``requested_chain`` specified and present in group → ``([requested_chain], None)``
    * group has exactly one chain → ``([group_chains[0]], None)``
    * group has multiple chains and no chain specified → ``(None, msg)`` where *msg*
      asks the user to specify which chain (or "all" for a symmetric edit).

    INVARIANT: never silently edits all copies when one was meant, or vice versa.
    A ``None`` chains return means the caller MUST ask the user before proceeding.
    """
    if requested_chain is not None:
        if requested_chain in group_chains:
            return [requested_chain], None
        return None, (
            f"Chain {requested_chain!r} is not in the group {group_chains!r}. "
            f"Specify one of {group_chains!r} or 'all' for a symmetric edit."
        )
    if len(group_chains) == 1:
        return [group_chains[0]], None
    chains_str = ", ".join(f"'{c}'" for c in group_chains)
    return None, (
        f"This row covers chains {chains_str}. "
        f"Specify which chain to edit, or 'all' to apply symmetrically to every copy."
    )


# ── Deterministic layout + presentation ─────────────────────────────────────────
# Config-driven command lists (config.CHIMERAX_*), applied by StructureBot — NOT
# LLM-generated, NOT the built-in `preset`.  apply_* run them error-first so a
# single failing command logs and the rest continue (an open is never aborted).

def lean_layout_commands(enabled: Optional[bool] = None) -> List[str]:
    """The once-per-session lean-window-layout commands (or [] when disabled)."""
    import config
    if enabled is None:
        enabled = getattr(config, "CHIMERAX_LEAN_LAYOUT", True)
    return list(config.CHIMERAX_LEAN_LAYOUT_COMMANDS) if enabled else []


def default_presentation_commands(enabled: Optional[bool] = None) -> List[str]:
    """The per-open default-presentation commands (or [] when disabled)."""
    import config
    if enabled is None:
        enabled = getattr(config, "CHIMERAX_DEFAULT_PRESENTATION", True)
    return list(config.CHIMERAX_DEFAULT_PRESENTATION_COMMANDS) if enabled else []


def _run_error_first(run_command, commands: List[str]) -> Tuple[List[str], List[str]]:
    """
    Run *commands* in order via *run_command* (a callable cmd -> dict-or-anything).
    A command that raises OR returns a dict with a truthy ``error`` is recorded as
    failed and execution CONTINUES.  Returns (attempted, failed).
    """
    attempted: List[str] = []
    failed:    List[str] = []
    for c in commands:
        attempted.append(c)
        try:
            r = run_command(c)
            if isinstance(r, dict) and r.get("error"):
                failed.append(c)
        except Exception:
            failed.append(c)
    return attempted, failed


def apply_lean_layout(
    run_command, enabled: Optional[bool] = None,
) -> Tuple[List[str], List[str]]:
    """Apply the lean window layout error-first.  Returns (attempted, failed).

    The once-per-session guard lives in the caller (e.g. the bridge), so this can
    be unit-tested directly; pass *enabled* to override the config switch.
    """
    return _run_error_first(run_command, lean_layout_commands(enabled))


def apply_default_presentation(
    run_command, enabled: Optional[bool] = None,
) -> Tuple[List[str], List[str]]:
    """Apply the per-open default presentation error-first.  Returns
    (attempted, failed)."""
    return _run_error_first(run_command, default_presentation_commands(enabled))
